project_id = "prscovdaelypkkviofoh"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.send-followup-reminders]
    verify_jwt = false
  [functions.transcribe-audio]
    verify_jwt = false
