project_id = "ozthojqaphifltilbbmx"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.send-followup-reminders]
    verify_jwt = false
  [functions.transcribe-audio]
    verify_jwt = false
  [functions.verify-site-password]
    verify_jwt = false
